### ISSUE TITLE
How to use this, i cant run application

### ISSUE THREAD

**Issue by salvadorc17** [IceYGO/ygosharp#1]
Hi, i have compiled this succesfully, but when i try to run application nothing happen, no error mesage, nothing, do you can tell me what else is requiered appart of the ygopro files??

**Comment by IceYGO** [comment]
Hi,

Have you tried to pass some arguments to the program?
cards.cdb, lflist.conf, ocgcore.dll (or libocgcore.so on linux) and the script folder are the only required files.

**Comment by salvadorc17** [comment]
Thats what i mean how to pass arguments, when i run (including all those files) window closes instantly

**Comment by IceYGO** [comment]
Can you try again using the latest version? The previous versions had the console and the console output disabled, so the program was running but invisible.

**Comment by salvadorc17** [comment]
I have tried it again today, but now im getting error reading banlist, in class BanlistManager

**Comment by Zayelion** [comment]
What is the **exact** command line string you are using to launch the application, and can you give us a screenshot of the folder that the application is in?

**Comment by salvadorc17** [comment]
Im not using command line parameters and the fodler is the debug folder, adding scripts/ ifflist and cards.cdb

**Comment by salvadorc17** [comment]
![ygosharp](https://cloud.githubusercontent.com/assets/13541889/13063680/8e6646d2-d418-11e5-8217-c0b677397c0b.png)

**Comment by Zayelion** [comment]
can I see a picture of the directory?

**Comment by salvadorc17** [comment]
Nevermind, tracked error and fixed, now opens normally, but it does not show message, it should show some text?

**Comment by Zayelion** [comment]
what was the error you tracked down and fixed? what was the fix?

**Comment by IceYGO** [comment]
ygosharp does not display any message by default. You can add `StandardStreamProtocol=true` to the arguments if you want some output.

**Comment by salvadorc17** [comment]
Which version of ygopro should i use to host a match?

**Comment by Zayelion** [comment]
https://github.com/IceYGO/ygosharp/blob/b770ecb4145b74d450c4e790d9dd34aa0f589be3/YGOSharp/Program.cs#L12

0x1338 (which is unreleased)
run it with the parameters `ClientVersion=0x1337` to allow percy clients to connect
