### ISSUE TITLE
compiling OCGCore

### ISSUE THREAD

**Issue by chatango-kotarou** [IceYGO/ygosharp#14]
CMake Error: CMake can not determine linker language for target: ocgcore
CMake Error: Cannot determine link language for target "ocgcore".
-- Generating done
-- Build files have been written to: /root/ygosharp/OCGCore
root@Host:~/ygosharp/OCGCore# cmake *.txt >> log2.txt
CMake Error at CMakeLists.txt:116 (add_library):
  Cannot find source file:

    ygopro-core/card.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: ocgcore
CMake Error: Cannot determine link language for target "ocgcore".

**Comment by IceYGO** [comment]
It looks like the `ygopro-core/card.cpp` file is missing.  
Did you also download the git submodules ?

If you are using the command line, you can use these commands:
```
git submodule init
git submodule update
```

**Comment by Ena-Shepherd** [comment]
Hello @IceYGO 
about submodules (continuing this thread) :
you need to sign with a github login to recurse-clone them, which is disabled since at least 3 years iirc.
Is this intended ?
ygopro-core leads to a 404.
