### ISSUE TITLE
MR4 (/protocol version 1340) support?

### ISSUE THREAD

**Issue by Demon0no** [IceYGO/ygosharp#16]
I tried to set up this server using the percy client (protocol version 1340) and it starts fine. I can connect no problem, but I get lua errors (`[string "./script/utility.lua"]:120: attempt to call a nil value (method 'GetReset')` and `[string "./script/utility.lua"]:72: attempt to call a nil value (field 'GetPlayerEffect')` mainly) and I can't activate pendulum monsters.
Does this server not support master rule 4, or am I just not setting it up correctly?

**Comment by IceYGO** [comment]
YGOSharp supports MR4. Maybe your scripts are not up to date or not loaded properly?
