### ISSUE TITLE
Linux Distrubition

### ISSUE THREAD

**Issue by Zayelion** [IceYGO/ygosharp#4]
@zh99998 hates windows, I was wondering if `ygosharp` compiles properly with mono. If so what are the directions for compiling it?

**Comment by IceYGO** [comment]
It does, at least on Debian 8.
After installing mono, the C# project can be compiled using the `xbuild` command while in the solution directory. It will compile all .NET assemblies in the `YGOSharp/bin/Debug/` subdirectory:

```
sudo apt-get install git mono-complete
git clone https://github.com/IceYGO/ygosharp
cd ygosharp
xbuild
```

`libocgcore.so` can be compiled using `cmake` and `g++`:

```
sudo apt-get install cmake make g++
git submodule init
git submodule update
cd OCGCore
mkdir build && cd build
cmake ..
make
```

The resulting `libocgcore.so` should be placed next to the compiled `YGOSharp.exe`. The server can then be used just like the Windows version.

**Comment by zh99998** [comment]
thanks
