### ISSUE TITLE
ygosharp is currently support percy 1.033A?

### ISSUE THREAD

**Issue by ekaomk** [IceYGO/ygosharp#8]
clean server and clean percy client. after press "Join" button, game not enter the room.
what i I've done nothing wrong?

![SS](https://s4.postimg.org/hy04thl2l/Capture.png)

**Comment by Buttys** [comment]
you might want to update this line https://github.com/IceYGO/ygosharp/blob/master/YGOSharp/Program.cs#L12

**Comment by ekaomk** [comment]
I checked that. it's 0x1339 same as old version.
I debug on line https://github.com/IceYGO/ygosharp/blob/master/YGOSharp/Player.cs#L138

**Comment by Buttys** [comment]
You might want to put your glasses on, percys client is 0x133A

**Comment by ekaomk** [comment]
Thank that works. and so sorry for i asked some fool question.
